# Existing US/Western aircraft data from original UnitDb.py
AircraftDb = [
    {
        "class_name": "F-35A Lightning II",
        "speed": 1200,
        "max_fuel": 18498,
        "fuel_rate": 1000,
        "range": 1350,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/478441/f-35a-lightning-ii/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/478441/f-35a-lightning-ii/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/478441/f-35a-lightning-ii/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "KC-135R Stratotanker",
        "speed": 530,
        "max_fuel": 200000,
        "fuel_rate": 5000,
        "range": 1303,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/174560/kc-135r-stratotanker/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/174560/kc-135r-stratotanker/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/174560/kc-135r-stratotanker/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "A-10C Thunderbolt II",
        "speed": 420,
        "max_fuel": 11000,
        "fuel_rate": 1000,
        "range": 695,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104490/a-10c-thunderbolt-ii/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104490/a-10c-thunderbolt-ii/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104490/a-10c-thunderbolt-ii/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "B-2 Spirit",
        "speed": 650,
        "max_fuel": 166999,
        "fuel_rate": 5000,
        "range": 6000,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104481/b-2-spirit/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104481/b-2-spirit/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104481/b-2-spirit/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "F-22 Raptor",
        "speed": 1500,
        "max_fuel": 18000,
        "fuel_rate": 1000,
        "range": 1600,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104506/f-22-raptor/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104506/f-22-raptor/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104506/f-22-raptor/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "C-130 Hercules",
        "speed": 350,
        "max_fuel": 61360,
        "fuel_rate": 5000,
        "range": 1700,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/1555054/c-130-hercules/",
            "max_fuel_src": "missing",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/1555054/c-130-hercules/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "C-17 Globemaster III",
        "speed": 570,
        "max_fuel": 181054,
        "fuel_rate": 5000,
        "range": 2785,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/1529726/c-17-globemaster-iii/",
            "max_fuel_src": "missing",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/478441/f-35a-lightning-ii/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "F-16 Fighting Falcon",
        "speed": 1500,
        "max_fuel": 12000,
        "fuel_rate": 1000,
        "range": 1740,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104505/f-16-fighting-falcon/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104505/f-16-fighting-falcon/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104505/f-16-fighting-falcon/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "F-15 Eagle",
        "speed": 1875,
        "max_fuel": 36200,
        "fuel_rate": 1000,
        "range": 3000,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104501/f-15-eagle/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104501/f-15-eagle/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104501/f-15-eagle/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "F/A-18 Hornet",
        "speed": 1381,
        "max_fuel": 14400,
        "fuel_rate": 1000,
        "range": 1275,
        "data_source": {
            "speed_src": "https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2383479/fa-18a-d-hornet-and-fa-18ef-super-hornet-strike-fighter/",
            "max_fuel_src": "missing",
            "fuel_rate_src": "missing",
            "range_src": "https://www.navy.mil/Resources/Fact-Files/Display-FactFiles/Article/2383479/fa-18a-d-hornet-and-fa-18ef-super-hornet-strike-fighter/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "B-52 Stratofortress",
        "speed": 650,
        "max_fuel": 312197,
        "fuel_rate": 5000,
        "range": 8800,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104465/b-52h-stratofortress/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104465/b-52h-stratofortress/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104465/b-52h-stratofortress/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "F-4 Phantom II",
        "speed": 1400,
        "max_fuel": 13890,
        "fuel_rate": 1000,
        "range": 1750,
        "data_source": {
            "speed_src": "https://www.holloman.af.mil/About/Fact-Sheets/Display/Article/317295/f-4-phantom-ii/",
            "max_fuel_src": "missing",
            "fuel_rate_src": "missing",
            "range_src": "https://www.holloman.af.mil/About/Fact-Sheets/Display/Article/317295/f-4-phantom-ii/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "B-1B Lancer",
        "speed": 900,
        "max_fuel": 265274,
        "fuel_rate": 5000,
        "range": 5100,
        "data_source": {
            "speed_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104500/b-1b-lancer/",
            "max_fuel_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104500/b-1b-lancer/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.af.mil/About-Us/Fact-Sheets/Display/Article/104500/b-1b-lancer/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "C-12 Huron",
        "speed": 284,
        "max_fuel": 4502,
        "fuel_rate": 300,
        "range": 1450,
        "data_source": {
            "speed_src": "https://www.5af.pacaf.af.mil/About-Us/Fact-Sheets/Display/Article/1482851/c-12-huron/",
            "max_fuel_src": "https://www.5af.pacaf.af.mil/About-Us/Fact-Sheets/Display/Article/1482851/c-12-huron/",
            "fuel_rate_src": "missing",
            "range_src": "https://www.5af.pacaf.af.mil/About-Us/Fact-Sheets/Display/Article/1482851/c-12-huron/",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "F-14 Tomcat",
        "speed": 1544,
        "max_fuel": 16200,
        "fuel_rate": 1000,
        "range": 2085,
        "data_source": {
            "speed_src": "https://www.history.navy.mil/content/history/museums/nnam/explore/collections/aircraft/f/f-14a-tomcat.html",
            "max_fuel_src": "missing",
            "fuel_rate_src": "missing",
            "range_src": "https://www.history.navy.mil/content/history/museums/nnam/explore/collections/aircraft/f/f-14a-tomcat.html",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "gallons/hour",
            "range_unit": "nm",
        },
    },
]
