# Chinese / Russian / European aircraft data
AircraftCnDb = [
    # --- Chinese Aircraft ---
    {
        "class_name": "J-20 Mighty Dragon",
        "speed": 1300,
        "max_fuel": 25000,
        "fuel_rate": 1200,
        "range": 1800,
        "country": "China",
        "role": "stealth_fighter",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "J-16",
        "speed": 1600,
        "max_fuel": 22500,
        "fuel_rate": 1300,
        "range": 2000,
        "country": "China",
        "role": "strike_fighter",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "J-10C Vigorous Dragon",
        "speed": 1350,
        "max_fuel": 14500,
        "fuel_rate": 1100,
        "range": 1600,
        "country": "China",
        "role": "multirole",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "JH-7 Flying Leopard",
        "speed": 1100,
        "max_fuel": 18000,
        "fuel_rate": 1400,
        "range": 1900,
        "country": "China",
        "role": "fighter_bomber",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "H-6K",
        "speed": 650,
        "max_fuel": 100000,
        "fuel_rate": 4000,
        "range": 3200,
        "country": "China",
        "role": "strategic_bomber",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Y-20 Kunpeng",
        "speed": 500,
        "max_fuel": 160000,
        "fuel_rate": 5000,
        "range": 4200,
        "country": "China",
        "role": "tanker_transport",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "J-11B",
        "speed": 1440,
        "max_fuel": 20000,
        "fuel_rate": 1200,
        "range": 1900,
        "country": "China",
        "role": "air_superiority",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    # --- Russian Aircraft ---
    {
        "class_name": "Su-57 Felon",
        "speed": 1600,
        "max_fuel": 22000,
        "fuel_rate": 1300,
        "range": 1900,
        "country": "Russia",
        "role": "stealth_fighter",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Su-35S Flanker-E",
        "speed": 1500,
        "max_fuel": 25400,
        "fuel_rate": 1400,
        "range": 2200,
        "country": "Russia",
        "role": "multirole",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Su-34 Fullback",
        "speed": 1200,
        "max_fuel": 26700,
        "fuel_rate": 1500,
        "range": 2100,
        "country": "Russia",
        "role": "strike_fighter",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "MiG-31 Foxhound",
        "speed": 1900,
        "max_fuel": 32000,
        "fuel_rate": 1800,
        "range": 1600,
        "country": "Russia",
        "role": "interceptor",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Tu-160 Blackjack",
        "speed": 1240,
        "max_fuel": 326000,
        "fuel_rate": 8000,
        "range": 7600,
        "country": "Russia",
        "role": "strategic_bomber",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Il-78 Midas",
        "speed": 500,
        "max_fuel": 210000,
        "fuel_rate": 5500,
        "range": 3900,
        "country": "Russia",
        "role": "tanker",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Su-30SM",
        "speed": 1320,
        "max_fuel": 21200,
        "fuel_rate": 1300,
        "range": 1900,
        "country": "Russia",
        "role": "multirole",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    # --- European Aircraft ---
    {
        "class_name": "Eurofighter Typhoon",
        "speed": 1550,
        "max_fuel": 13700,
        "fuel_rate": 1100,
        "range": 1600,
        "country": "Europe",
        "role": "multirole",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Dassault Rafale",
        "speed": 1380,
        "max_fuel": 11900,
        "fuel_rate": 1000,
        "range": 2000,
        "country": "France",
        "role": "multirole",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Saab Gripen E",
        "speed": 1370,
        "max_fuel": 7500,
        "fuel_rate": 800,
        "range": 2200,
        "country": "Sweden",
        "role": "multirole",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "Panavia Tornado GR4",
        "speed": 1490,
        "max_fuel": 15300,
        "fuel_rate": 1300,
        "range": 1700,
        "country": "Europe",
        "role": "strike",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "A400M Atlas",
        "speed": 420,
        "max_fuel": 120000,
        "fuel_rate": 4500,
        "range": 4800,
        "country": "Europe",
        "role": "tanker_transport",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
    {
        "class_name": "F-15I Ra'am",
        "speed": 1650,
        "max_fuel": 28000,
        "fuel_rate": 1200,
        "range": 2400,
        "country": "Israel",
        "role": "strike_fighter",
        "data_source": {
            "speed_src": "estimated from open sources",
            "max_fuel_src": "estimated from open sources",
            "fuel_rate_src": "estimated",
            "range_src": "estimated from open sources",
        },
        "units": {
            "speed_unit": "mph",
            "max_fuel_unit": "lbs",
            "fuel_rate_unit": "lbs/hour",
            "range_unit": "nm",
        },
    },
]
