# Mobile ground combat platforms. Ranges are approximate nautical miles.
GroundVehicleDb = [
    {
        "class_name": "HIMARS",
        "speed": 45,
        "range": 2,
        "detection_range_nm": 15,
        "radar_on": False,
        "rcs": 2.0,
        "jammer_power": 0.0,
        "jammer_range_nm": 0.0,
        "ew_resistance": 0.1,
        "comms_on": True,
        "comms_range_nm": 90.0,
        "datalink": True,
        "command_node": False,
        "comms_power": 1.0,
        "comms_resistance": 0.15,
        "role": "rocket_artillery",
        "country": "US",
    },
    {
        "class_name": "M270 MLRS",
        "speed": 35,
        "range": 2,
        "detection_range_nm": 12,
        "radar_on": False,
        "rcs": 2.5,
        "jammer_power": 0.0,
        "jammer_range_nm": 0.0,
        "ew_resistance": 0.1,
        "comms_on": True,
        "comms_range_nm": 80.0,
        "datalink": True,
        "command_node": False,
        "comms_power": 1.0,
        "comms_resistance": 0.12,
        "role": "rocket_artillery",
        "country": "US",
    },
    {
        "class_name": "Iskander TEL",
        "speed": 40,
        "range": 2,
        "detection_range_nm": 20,
        "radar_on": False,
        "rcs": 3.0,
        "jammer_power": 0.0,
        "jammer_range_nm": 0.0,
        "ew_resistance": 0.15,
        "comms_on": True,
        "comms_range_nm": 110.0,
        "datalink": True,
        "command_node": False,
        "comms_power": 1.1,
        "comms_resistance": 0.2,
        "role": "ballistic_missile_launcher",
        "country": "Russia",
    },
    {
        "class_name": "DF-16 TEL",
        "speed": 35,
        "range": 2,
        "detection_range_nm": 20,
        "radar_on": False,
        "rcs": 3.5,
        "jammer_power": 0.0,
        "jammer_range_nm": 0.0,
        "ew_resistance": 0.15,
        "comms_on": True,
        "comms_range_nm": 120.0,
        "datalink": True,
        "command_node": False,
        "comms_power": 1.1,
        "comms_resistance": 0.2,
        "role": "ballistic_missile_launcher",
        "country": "China",
    },
    {
        "class_name": "PCL-191",
        "speed": 40,
        "range": 2,
        "detection_range_nm": 15,
        "radar_on": False,
        "rcs": 2.5,
        "jammer_power": 0.0,
        "jammer_range_nm": 0.0,
        "ew_resistance": 0.12,
        "comms_on": True,
        "comms_range_nm": 100.0,
        "datalink": True,
        "command_node": False,
        "comms_power": 1.0,
        "comms_resistance": 0.18,
        "role": "rocket_artillery",
        "country": "China",
    },
    {
        "class_name": "Command Vehicle",
        "speed": 35,
        "range": 1,
        "detection_range_nm": 8,
        "radar_on": False,
        "rcs": 2.0,
        "jammer_power": 0.0,
        "jammer_range_nm": 0.0,
        "ew_resistance": 0.25,
        "comms_on": True,
        "comms_range_nm": 160.0,
        "datalink": True,
        "command_node": True,
        "comms_power": 1.3,
        "comms_resistance": 0.35,
        "role": "command_node",
        "country": "Generic",
    },
    {
        "class_name": "Mobile Radar Vehicle",
        "speed": 35,
        "range": 1,
        "detection_range_nm": 80,
        "radar_on": True,
        "rcs": 2.8,
        "jammer_power": 0.0,
        "jammer_range_nm": 0.0,
        "ew_resistance": 0.25,
        "comms_on": True,
        "comms_range_nm": 140.0,
        "datalink": True,
        "command_node": True,
        "comms_power": 1.2,
        "comms_resistance": 0.3,
        "role": "mobile_radar",
        "country": "Generic",
    },
    {
        "class_name": "SAM Launcher Vehicle",
        "speed": 35,
        "range": 1,
        "detection_range_nm": 60,
        "radar_on": True,
        "rcs": 2.8,
        "jammer_power": 0.05,
        "jammer_range_nm": 15.0,
        "ew_resistance": 0.25,
        "comms_on": True,
        "comms_range_nm": 120.0,
        "datalink": True,
        "command_node": False,
        "comms_power": 1.1,
        "comms_resistance": 0.25,
        "role": "mobile_sam",
        "country": "Generic",
    },
]
