# Ship database - all values notional unless otherwise sourced
ShipDb = [
    # --- US / NATO ---
    {
        "class_name": "Aircraft Carrier",
        "speed": 35,
        "max_fuel": 25200000,
        "fuel_rate": 1000000,
        "range": 8000,
        "country": "US",
    },
    {
        "class_name": "Destroyer",
        "speed": 40,
        "max_fuel": 3500000,
        "fuel_rate": 100000,
        "range": 5000,
        "country": "US",
    },
    {
        "class_name": "Frigate",
        "speed": 35,
        "max_fuel": 2800000,
        "fuel_rate": 80000,
        "range": 4500,
        "country": "US",
    },
    {
        "class_name": "Corvette",
        "speed": 32,
        "max_fuel": 1400000,
        "fuel_rate": 60000,
        "range": 3500,
        "country": "US",
    },
    {
        "class_name": "Amphibious Assault Ship",
        "speed": 25,
        "max_fuel": 8400000,
        "fuel_rate": 200000,
        "range": 6000,
        "country": "US",
    },
    {
        "class_name": "Patrol Boat",
        "speed": 40,
        "max_fuel": 350000,
        "fuel_rate": 30000,
        "range": 1500,
        "country": "US",
    },
    # --- Chinese Navy (PLAN) ---
    {
        "class_name": "Type 055 Destroyer",
        "speed": 34,
        "max_fuel": 4000000,
        "fuel_rate": 110000,
        "range": 5500,
        "country": "China",
    },
    {
        "class_name": "Type 052D Destroyer",
        "speed": 30,
        "max_fuel": 3200000,
        "fuel_rate": 95000,
        "range": 4500,
        "country": "China",
    },
    {
        "class_name": "Type 054A Frigate",
        "speed": 27,
        "max_fuel": 2200000,
        "fuel_rate": 70000,
        "range": 4000,
        "country": "China",
    },
    {
        "class_name": "Type 003 Fujian Carrier",
        "speed": 32,
        "max_fuel": 24000000,
        "fuel_rate": 950000,
        "range": 7500,
        "country": "China",
    },
    # --- Russian Navy ---
    {
        "class_name": "Kirov-class Battlecruiser",
        "speed": 32,
        "max_fuel": 6000000,
        "fuel_rate": 180000,
        "range": 6000,
        "country": "Russia",
    },
    {
        "class_name": "Admiral Gorshkov-class Frigate",
        "speed": 30,
        "max_fuel": 2600000,
        "fuel_rate": 75000,
        "range": 4200,
        "country": "Russia",
    },
    {
        "class_name": "Admiral Kuznetsov Carrier",
        "speed": 29,
        "max_fuel": 22000000,
        "fuel_rate": 900000,
        "range": 7000,
        "country": "Russia",
    },
    # --- European ---
    {
        "class_name": "Type 45 Destroyer",
        "speed": 30,
        "max_fuel": 3400000,
        "fuel_rate": 100000,
        "range": 5000,
        "country": "UK",
    },
    {
        "class_name": "Horizon-class Frigate",
        "speed": 29,
        "max_fuel": 2500000,
        "fuel_rate": 72000,
        "range": 4300,
        "country": "France/Italy",
    },
]
