# Weapon templates for loadout generation
# Each entry defines a weapon type that can be attached to platforms
WeaponDb = [
    # --- Air-to-Air Missiles ---
    {
        "class_name": "AIM-120D AMRAAM",
        "speed": 3000,
        "current_fuel": 500,
        "max_fuel": 500,
        "fuel_rate": 500,
        "range": 120,
        "lethality": 0.70,
        "type": "aam",
        "country": "US",
    },
    {
        "class_name": "AIM-9X Sidewinder",
        "speed": 2500,
        "current_fuel": 100,
        "max_fuel": 100,
        "fuel_rate": 100,
        "range": 20,
        "lethality": 0.60,
        "type": "aam",
        "country": "US",
    },
    {
        "class_name": "PL-15",
        "speed": 3000,
        "current_fuel": 450,
        "max_fuel": 450,
        "fuel_rate": 450,
        "range": 110,
        "lethality": 0.70,
        "type": "aam",
        "country": "China",
    },
    {
        "class_name": "PL-10",
        "speed": 2500,
        "current_fuel": 90,
        "max_fuel": 90,
        "fuel_rate": 90,
        "range": 20,
        "lethality": 0.65,
        "type": "aam",
        "country": "China",
    },
    {
        "class_name": "R-77",
        "speed": 2800,
        "current_fuel": 350,
        "max_fuel": 350,
        "fuel_rate": 350,
        "range": 80,
        "lethality": 0.65,
        "type": "aam",
        "country": "Russia",
    },
    {
        "class_name": "R-73",
        "speed": 2500,
        "current_fuel": 80,
        "max_fuel": 80,
        "fuel_rate": 80,
        "range": 20,
        "lethality": 0.60,
        "type": "aam",
        "country": "Russia",
    },
    {
        "class_name": "Meteor",
        "speed": 3500,
        "current_fuel": 600,
        "max_fuel": 600,
        "fuel_rate": 600,
        "range": 140,
        "lethality": 0.75,
        "type": "aam",
        "country": "Europe",
    },
    # --- Air-to-Ground / Anti-Ship Missiles ---
    {
        "class_name": "AGM-158 JASSM",
        "speed": 600,
        "current_fuel": 1000,
        "max_fuel": 1000,
        "fuel_rate": 100,
        "range": 500,
        "lethality": 0.80,
        "type": "agm",
        "country": "US",
    },
    {
        "class_name": "AGM-88 HARM",
        "speed": 1800,
        "current_fuel": 300,
        "max_fuel": 300,
        "fuel_rate": 200,
        "range": 80,
        "lethality": 0.60,
        "type": "arm",
        "country": "US",
    },
    {
        "class_name": "YJ-12",
        "speed": 2400,
        "current_fuel": 400,
        "max_fuel": 400,
        "fuel_rate": 300,
        "range": 150,
        "lethality": 0.75,
        "type": "asm",
        "country": "China",
    },
    {
        "class_name": "KD-20",
        "speed": 500,
        "current_fuel": 2000,
        "max_fuel": 2000,
        "fuel_rate": 120,
        "range": 800,
        "lethality": 0.80,
        "type": "agm",
        "country": "China",
    },
    {
        "class_name": "Kh-31P",
        "speed": 2000,
        "current_fuel": 250,
        "max_fuel": 250,
        "fuel_rate": 200,
        "range": 60,
        "lethality": 0.55,
        "type": "arm",
        "country": "Russia",
    },
    {
        "class_name": "Kh-59MK2",
        "speed": 600,
        "current_fuel": 800,
        "max_fuel": 800,
        "fuel_rate": 100,
        "range": 300,
        "lethality": 0.75,
        "type": "agm",
        "country": "Russia",
    },
    # --- Ship-launched SAMs ---
    {
        "class_name": "SM-6",
        "speed": 3500,
        "current_fuel": 600,
        "max_fuel": 600,
        "fuel_rate": 500,
        "range": 200,
        "lethality": 0.70,
        "type": "sam",
        "country": "US",
    },
    {
        "class_name": "SM-2",
        "speed": 3000,
        "current_fuel": 400,
        "max_fuel": 400,
        "fuel_rate": 400,
        "range": 90,
        "lethality": 0.65,
        "type": "sam",
        "country": "US",
    },
    {
        "class_name": "HQ-9B Naval",
        "speed": 3000,
        "current_fuel": 500,
        "max_fuel": 500,
        "fuel_rate": 450,
        "range": 150,
        "lethality": 0.65,
        "type": "sam",
        "country": "China",
    },
    {
        "class_name": "Sea Ceptor",
        "speed": 2500,
        "current_fuel": 150,
        "max_fuel": 150,
        "fuel_rate": 150,
        "range": 25,
        "lethality": 0.60,
        "type": "sam",
        "country": "UK",
    },
    # --- Ground-launched rockets and missiles ---
    {
        "class_name": "GMLRS",
        "speed": 1800,
        "current_fuel": 240,
        "max_fuel": 240,
        "fuel_rate": 160,
        "range": 43,
        "lethality": 0.70,
        "type": "rocket_artillery",
        "country": "US",
    },
    {
        "class_name": "ATACMS",
        "speed": 3000,
        "current_fuel": 500,
        "max_fuel": 500,
        "fuel_rate": 220,
        "range": 160,
        "lethality": 0.82,
        "type": "ballistic_missile",
        "country": "US",
    },
    {
        "class_name": "PrSM",
        "speed": 3500,
        "current_fuel": 600,
        "max_fuel": 600,
        "fuel_rate": 240,
        "range": 270,
        "lethality": 0.85,
        "type": "ballistic_missile",
        "country": "US",
    },
    {
        "class_name": "Iskander",
        "speed": 4200,
        "current_fuel": 700,
        "max_fuel": 700,
        "fuel_rate": 260,
        "range": 270,
        "lethality": 0.86,
        "type": "ballistic_missile",
        "country": "Russia",
    },
    {
        "class_name": "DF-16",
        "speed": 4500,
        "current_fuel": 900,
        "max_fuel": 900,
        "fuel_rate": 300,
        "range": 540,
        "lethality": 0.88,
        "type": "ballistic_missile",
        "country": "China",
    },
    {
        "class_name": "PCL-191 Rocket",
        "speed": 2600,
        "current_fuel": 420,
        "max_fuel": 420,
        "fuel_rate": 200,
        "range": 190,
        "lethality": 0.78,
        "type": "rocket_artillery",
        "country": "China",
    },
]
